feat(mobs): implemented squirrel mob behaviour
North-Nomads/TundraGame pull request #116
Opened 2023-04-09 09:15 UTC by EveRWhateveR-python

2023-04-09 09:49 UTC, TaggedDev requested changes

2023-04-09 09:49 UTC, TaggedDev commented on TundraTD/Assets/Scripts/Mobs/MobsBehaviour/Squirrel/SquirrelBehaviour.cs
> +                        float _distanceToTree = Vector3.Distance(this.transform.position, _tree.gameObject.transform.position);
```suggestion
            float _minDistance = 10000;
            float scanRadius = 1000f;
            TreeLayerIndex = 10; // Set layer **mask** index here
            Collider[] _allTrees = Physics.OverlapSphere(this.transform.position, scanRadius, 1 << TreeLayerIndex);
            foreach(var _tree in _allTrees)
            {
                if (_isFirstTree)
                {
                        float _distanceToTree = Vector3.Distance(this.transform.position, _tree.gameObject.transform.position);
```

2023-04-09 09:49 UTC, TaggedDev commented on TundraTD/Assets/Scripts/Mobs/MobsBehaviour/Squirrel/SquirrelBehaviour.cs
> +                        float _distanceToTree = Vector3.Distance(this.transform.position, _tree.gameObject.transform.position);
Переименовать _isFirstTree в _isOnTree

2023-04-09 09:49 UTC, TaggedDev commented on TundraTD/Assets/Scripts/Mobs/MobsBehaviour/Squirrel/SquirrelBehaviour.cs
> +                        float _distanceToTree = Vector3.Distance(this.transform.position, _tree.gameObject.transform.position);
```
1 << TreeLayerIndex | 1 << GatesLayerIndex
```

2023-04-09 09:49 UTC, TaggedDev commented on TundraTD/Assets/Scripts/Mobs/MobsBehaviour/Squirrel/SquirrelBehaviour.cs
> +        private Vector3 _treeCords;
Удалить, так как белка теперь не возвращается назад

2023-04-09 09:49 UTC, TaggedDev commented on TundraTD/Assets/Scripts/Mobs/MobsBehaviour/Squirrel/SquirrelBehaviour.cs
> +                        && this.transform.position.z < _tree.transform.position.z
```suggestion
Vector3.Dot(transform.position  - _tree.transform.position, _tree.transform.position) > 0
```
> 0 спереди
< 0 сзади
= 0 сбоку

2023-04-09 09:49 UTC, TaggedDev commented on TundraTD/Assets/Scripts/Mobs/MobsBehaviour/Squirrel/SquirrelBehaviour.cs
> +                        && Mathf.Abs(this.transform.position.x - _tree.transform.position.x) < 5)
```suggestion
float secondaryScanRadius = ScanRadius * 0.4f 
Physics.OverlapSphere(transform.position, secondaryScanRadius)
```

2023-04-09 09:49 UTC, TaggedDev commented on TundraTD/Assets/Scripts/Mobs/MobsBehaviour/Squirrel/SquirrelBehaviour.cs
> +                        float _distanceToTree = Vector3.Distance(this.transform.position, _tree.gameObject.transform.position);
```suggestion
                        float treeDistance = Vector3.Distance(transform.position, _tree.gameObject.transform.position);
```

2023-04-09 09:49 UTC, TaggedDev commented on TundraTD/Assets/Scripts/Mobs/MobsBehaviour/Squirrel/SquirrelBehaviour.cs
> +            if (_goToGates)
Переименовать переменную так, чтобы она отвечала True или False 

напр: IsGoingToGates

2023-04-25 13:58 UTC, IOExcept10n approved these changes

2023-04-25 15:06 UTC, TaggedDev approved these changes

2023-04-25 15:07 UTC, merged