Lightning strike
North-Nomads/TundraGame pull request #118
Opened 2023-04-11 18:26 UTC by GalteXx

2023-04-14 13:44 UTC, TaggedDev requested changes

2023-04-15 12:02 UTC, TaggedDev requested changes

2023-04-15 12:02 UTC, TaggedDev commented on TundraTD/Assets/Scripts/Spells/SpellClasses/LightningCrystallSpell.cs
> +        _mobs.Where(mob => !mob.gameObject.activeSelf).ToList().ForEach(mob => _mobs.Remove(mob));
Насколько я понял, эта строчка убирает из списка мобов тех, что уже успели умереть. Я бы предпочел избежать в FixedUpdate() приведения данных к списку, так как это тяжелая операция. Мне кажется лучше будет просто проходиться через for i (...) и внутри проверять на activeself. Тогда у нас в целом будет один цикл for для обоих итераций

```suggestion
        for (int i = 0; i < _mobs.Length; i++)
        {
            var mob = _mobs[i];
            if (!mob.gameObject.activeSelf)
            {
                _mobs.RemoveAt(i);
            }
            else 
            {
            var mobPosition = mob.transform.position;
              mob.AddForce(new Vector3 (mobPosition .x - transform.position.x, mobPosition.y - transform.position.y, mobPosition.z - transform.position.z).normalized * pullForce * -1, ForceMode.Force));
            }
        }
```

2023-04-15 12:02 UTC, TaggedDev commented on TundraTD/Assets/Scripts/Spells/SpellClasses/LightningCrystallSpell.cs
> +        _mobs.Where(mob => !mob.gameObject.activeSelf).ToList().ForEach(mob => _mobs.Remove(mob));
А ещё, я думаю, что мы можем использовать для этого эффект Graviation, который будет принимать Vector3 targetPosition, к которому будет притягиваться моб. Но возможно, это излишнее

2023-04-15 12:02 UTC, TaggedDev commented on TundraTD/Assets/Scripts/Spells/SpellClasses/LightningCrystallSpell.cs
> +            (mob.transform.position.x - transform.position.x, mob.transform.position.y - transform.position.y, mob.transform.position.z - transform.position.z).normalized * pullForce * -1, ForceMode.
см. код выше

2023-04-15 12:02 UTC, TaggedDev commented on TundraTD/Assets/Scripts/Spells/SpellClasses/LightningCrystallSpell.cs
> +                _mobs.Add(mob);
А зачем это делать на старте? Так критично? Можно попробовать вообще не использовать метод Start()

2023-04-15 12:04 UTC, GalteXx commented on TundraTD/Assets/Scripts/Spells/SpellClasses/LightningCrystallSpell.cs
> +    private float t = 0;
полагаю что это просто для "красоты и понятности". Предпочитаю сваливать все объявления в одном месте

2023-04-15 12:06 UTC, GalteXx commented on TundraTD/Assets/Scripts/Spells/SpellClasses/LightningCrystallSpell.cs
> +                _mobs.Add(mob);
нужно. Иначе мобы которые УЖЕ НАХОДЯТСЯ в зоне действия, при появлении кристалла, не будут засчитанны.

2023-04-16 10:13 UTC, GalteXx commented on TundraTD/Assets/Scripts/Spells/SpellClasses/LightningSpell/StaticCharge.cs
> +    }
Удалил весь файл

2023-04-16 10:55 UTC, GalteXx commented on TundraTD/Assets/Scripts/Spells/SpellClasses/BallLightningSpell.cs
> +        }
В результате дискуссии коллективным решением оставляем alloc

2023-04-17 07:20 UTC, TaggedDev approved these changes

2023-04-24 09:34 UTC, merged