Point movement system
North-Nomads/TundraGame pull request #119
Opened 2023-04-13 18:55 UTC by TaggedDev

Реализация системы передвижения от точки до точки

2023-04-14 03:17 UTC, IOExcept10n requested changes

2023-04-14 03:17 UTC, IOExcept10n commented on TundraTD/Assets/Scripts/Mobs/MobEffects/DistractEffect.cs
> +            if (mob.WaypointRoute[mob.CurrentWaypointIndex].transform.position == _target.transform.position)
Проверка вектора на полное равенство – неправильный метод определения достижения цели. Лучше вычесть один вектор из другого, найти длину и сравнить полученное расстояние с каким-либо пороговым значением

2023-04-14 03:17 UTC, IOExcept10n commented on TundraTD/Assets/Scripts/Mobs/MobsBehaviour/MobBehaviour.cs
> +            _waypointRoute = route.WayPoints;
Насколько я понимаю, у нас есть один список, передаваемый всем мобам. При достижении точки они либо увеличивают счётчик, либо удаляют точку. При удалении точки есть одна проблема: список общий и разделён на всех, она удалится у всех. На данный момент такая ошибка невозможна из-за того, что векторы позиции сравниваются напрямую (это никогда не произойдёт). Но если действительно правильно реализовать сравнение, то это повлечёт за собой ошибки. Ещё одна проблема заключается в том, что если копировать список на каждого моба, то это потребует много памяти, лучше так не делать

2023-04-14 04:23 UTC, TaggedDev commented on TundraTD/Assets/Scripts/Mobs/MobsBehaviour/MobBehaviour.cs
> +            _waypointRoute = route.WayPoints;
Не совсем. 

У нас есть общий список, который передается в портал (Route.cs), который содержит точки (WayPoint.cs). У каждого моба есть ссылка на этот список, что верно, но и индексацию моб ведет свою персональную.

Когда моб достигает точки, триггер у waypoint'а вызывает функцию MobBehaviour.HandleWaypointApproaching(), которая только увеличивает текущий индекс у конкретного моба.

Вставка и удаление точки происходит только в эффекте Distraction, который сейчас не используется. Но действительно, такое поведение будет неправильно сказываться на всех мобах, так как эта точка будет доступна для всех противников

2023-04-14 04:25 UTC, TaggedDev commented on TundraTD/Assets/Scripts/Mobs/MobsBehaviour/MobBehaviour.cs
> +            _waypointRoute = route.WayPoints;
Вероятно на данном этапе можно просто удалить неиспользуемую функцию, тогда это временно избавит нас от этой проблемы

2023-04-14 10:06 UTC, IOExcept10n commented on TundraTD/Assets/Scripts/Mobs/MobEffects/Effect.cs
> +            Debug.Log($"{CurrentTicksAmount}/{MaxTicksAmount}");
Дебаг ещё актуален?

2023-04-14 10:11 UTC, IOExcept10n commented on TundraTD/Assets/Scripts/Mobs/MobEffects/StunEffect.cs
> +                mob.CurrentEffects.Remove(stun);
Не совсем понятна эта логика. По сути, мы тут обновляем эффект, но очень неэффективным способом, так как ей приходится сначала пройтись по списку в поисках эффекта, а потом пройтись ещё раз для его удаления. Вопроса 2:
1. Точно ли нужно его удалять? Может просто новый не накладывать?
2. Почему бы не отменять аттач этого эффекта, обновляя уже существующий, вместо таких манипуляций?

2023-04-14 10:17 UTC, TaggedDev commented on TundraTD/Assets/Scripts/Mobs/MobEffects/Effect.cs
> +            Debug.Log($"{CurrentTicksAmount}/{MaxTicksAmount}");
Удалены в #121

2023-04-14 10:18 UTC, TaggedDev commented on TundraTD/Assets/Scripts/Mobs/MobEffects/StunEffect.cs
> +                mob.CurrentEffects.Remove(stun);
С ним кстати и был связан #115

2023-04-14 11:01 UTC, IOExcept10n requested changes

2023-04-14 11:01 UTC, IOExcept10n commented on TundraTD/Assets/Scripts/Spells/SpellClasses/StoneGrenadeSpell.cs
> +                var lerpedY = Mathf.Lerp(0, 1, time / liftTime);
Возможно, имеет смысл назвать переменную понятнее
```suggestion
                var interpolatedY = Mathf.Lerp(0, 1, time / liftTime);
```

2023-04-14 11:12 UTC, TaggedDev commented on TundraTD/Assets/Scripts/Mobs/MobsBehaviour/MobBehaviour.cs
> +        private WayPoint[] _waypointRoute = new WayPoint[100];
Он разве не будет Null изначально?

2023-04-14 14:53 UTC, IOExcept10n commented on TundraTD/Assets/Scripts/Mobs/MobsBehaviour/MobBehaviour.cs
> +        private WayPoint[] _waypointRoute = new WayPoint[100];
Если ты присваиваешь ему значение, то не будет, это значение будет при создании объекта присвоено

2023-04-15 11:01 UTC, IOExcept10n approved these changes

2023-04-15 19:43 UTC, merged